# Generated by Django 4.1.7 on 2023-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listings",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("host_id", models.IntegerField(blank=True, null=True)),
                ("host_name", models.TextField(blank=True, null=True)),
                ("neighbourhood_group", models.TextField(blank=True, null=True)),
                ("neighbourhood", models.TextField(blank=True, null=True)),
                ("latitude", models.TextField(blank=True, null=True)),
                ("longitude", models.TextField(blank=True, null=True)),
                ("room_type", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("minimum_nights", models.IntegerField(blank=True, null=True)),
                ("number_of_reviews", models.IntegerField(blank=True, null=True)),
                ("last_review", models.TextField(blank=True, null=True)),
                ("reviews_per_month", models.TextField(blank=True, null=True)),
                (
                    "calculated_host_listings_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("availability_365", models.IntegerField(blank=True, null=True)),
                ("number_of_reviews_ltm", models.IntegerField(blank=True, null=True)),
                ("license", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "listings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Neighbourhoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("neighbourhood_group", models.TextField(blank=True, null=True)),
                ("neighbourhood", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "neighbourhoods",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_id", models.IntegerField(blank=True, null=True)),
                ("date", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "reviews",
                "managed": False,
            },
        ),
    ]
