# Generated by Django 3.1.6 on 2023-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire_items',
            name='volume',
            field=models.FloatField(),
        ),
    ]
