# Generated by Django 3.1.6 on 2023-02-24 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='additional_address',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='country',
        ),
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit comporter 10 chiffres.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='HomeToMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_area', models.DecimalField(decimal_places=2, max_digits=4)),
                ('address', models.TextField()),
                ('additional_address', models.TextField(blank=True)),
                ('code_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Le code postal doit comporter 5 chiffres.', regex='^\\d{5}$')])),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('customer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.customers')),
            ],
        ),
    ]
