# Generated by Django 4.1.7 on 2023-03-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0008_inventaire_items_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventaire_items",
            name="place",
            field=models.CharField(max_length=50),
        ),
    ]
