# Generated by Django 4.1.7 on 2023-03-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0012_inventaire_items_thumbnail_i_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=50)),
                (
                    "image_piece",
                    models.ImageField(blank=True, null=True, upload_to="img_pieces"),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="inventaire_items",
            old_name="thumbnail_i",
            new_name="image_item",
        ),
        migrations.RemoveField(
            model_name="inventaire_items",
            name="thumbnail_p",
        ),
    ]
