# Generated by Django 4.1.7 on 2023-03-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0013_place_rename_thumbnail_i_inventaire_items_image_item_and_more"),
    ]
