# Generated by Django 4.1.7 on 2023-03-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0014_alter_inventaire_items_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventaire_items",
            name="piece_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventaire.place",
            ),
        ),
        migrations.AlterField(
            model_name="inventaire_items",
            name="place",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
