# Generated by Django 4.1.7 on 2023-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0017_inventaire_items_piece_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventaire_items",
            name="piece_fk",
        ),
        migrations.AddField(
            model_name="inventaire_items",
            name="place_item",
            field=models.ManyToManyField(to="inventaire.place"),
        ),
    ]
