# Generated by Django 4.1.7 on 2023-03-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0020_inventaire_items_piecefk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hometomove",
            name="customer_fk",
        ),
        migrations.RemoveField(
            model_name="housing_inventory",
            name="HomeToMove_fk",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Customers",
        ),
        migrations.DeleteModel(
            name="HomeToMove",
        ),
        migrations.DeleteModel(
            name="Housing_inventory",
        ),
    ]
