# Generated by Django 4.1.7 on 2023-03-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0024_alter_piece_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="piece",
            name="slug",
        ),
    ]
