# Generated by Django 4.1.7 on 2023-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0027_remove_piece_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
