# Generated by Django 4.1.7 on 2023-03-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0028_piece_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventaire_items",
            name="piecefk",
        ),
        migrations.RemoveField(
            model_name="piece",
            name="slug",
        ),
    ]
