# Generated by Django 4.1.7 on 2023-03-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0029_remove_inventaire_items_piecefk_remove_piece_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="slug",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
