# Generated by Django 4.1.7 on 2023-04-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventaire', '0078_remove_détaillistingclient_articlesclient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesV2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomArticle', models.CharField(max_length=100)),
                ('slugArticle', models.CharField(max_length=100)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imageArticle', models.ImageField(blank=True, null=True, upload_to='img_inventaire')),
                ('nomPieceArticle', models.CharField(blank=True, max_length=50, null=True)),
                ('Piece_id', models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='inventaire.piece')),
            ],
            options={
                'verbose_name_plural': 'Liste complète des articles',
            },
        ),
        migrations.CreateModel(
            name='MissionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteArticleA', models.IntegerField(default=1)),
                ('articlesMission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaireArticles.articlesv2')),
                ('pieceMissionA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.piece')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DétailListingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articlesClient', models.ManyToManyField(to='inventaireArticles.missionarticle')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Détail article par client',
                'verbose_name_plural': 'Détail articles par client',
            },
        ),
    ]
