# Generated by Django 4.1.7 on 2023-03-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0009_alter_inventaire_items_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="nb_Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counter", models.IntegerField(default=0)),
                (
                    "items",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventaire.inventaire_items",
                    ),
                ),
            ],
        ),
    ]
