# Generated by Django 4.1.7 on 2023-03-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0010_nb_article"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="nb_Article",
            new_name="Article",
        ),
    ]
