# Generated by Django 4.1.7 on 2023-03-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0015_inventaire_items_piece_fk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventaire_items",
            name="piece_fk",
        ),
    ]
