# Generated by Django 4.1.7 on 2023-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0032_remove_articles_place_articles_lieu'),
    ]


