# Generated by Django 4.1.7 on 2023-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0036_articles_nompiecearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='imagePiece',
            field=models.ImageField(blank=True, null=True, upload_to='media/img_pieces'),
        ),
    ]
