# Generated by Django 4.1.7 on 2023-04-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0041_missionpiece'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='articles',
            new_name='piecesPanier',
        ),
    ]
