# Generated by Django 4.1.7 on 2023-04-05 11:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaire', '0043_alter_panier_piecespanier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Panier',
            new_name='CommandeClient',
        ),
    ]
