# Generated by Django 4.1.7 on 2023-04-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0049_articlesv2'),
    ]
