# Generated by Django 4.1.7 on 2023-04-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0051_piece_articles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionarticle',
            name='articlesMission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.articlesv2'),
        ),
        migrations.AlterField(
            model_name='missionarticle',
            name='pieceMission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.piece'),
        ),
    ]
