# Generated by Django 4.1.7 on 2023-04-07 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaire', '0052_alter_missionarticle_articlesmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DétailListingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionValidee', models.BooleanField(default=False)),
                ('dateMissionValisee', models.DateTimeField(blank=True, null=True)),
                ('articlesClient', models.ManyToManyField(to='inventaire.articlesv2')),
                ('piecesPanier', models.ManyToManyField(to='inventaire.missionpiece')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
