# Generated by Django 4.1.7 on 2023-04-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0056_remove_piece_articles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesv2',
            name='Piece_id',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='inventaire.piece'),
        ),
    ]
