# Generated by Django 4.1.7 on 2023-04-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0061_alter_articlesv2_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionarticle',
            old_name='pieceMission',
            new_name='pieceMissionA',
        ),
    ]
