# Generated by Django 4.2 on 2023-04-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0063_remove_piece_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="détaillistingclient",
            name="articlesClient",
            field=models.ManyToManyField(to="inventaire.missionarticle"),
        ),
    ]
