# Generated by Django 4.1.7 on 2023-04-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0065_rename_quantitearticle_missionarticle_quantitearticlea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
