# Generated by Django 4.1.7 on 2023-04-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0068_remove_articlesv2_utilisateur_and_more'),
    ]

