# Generated by Django 4.1.7 on 2023-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="created",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="ordered",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="ordered_date",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="updated",
        ),
        migrations.AddField(
            model_name="order",
            name="ordered_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
