# Generated by Django 4.1.7 on 2023-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0022_mission_contenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
