# Generated by Django 4.1.7 on 2023-02-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0006_auto_20230224_1834"),
    ]

    operations = [
        migrations.AddField(
            model_name="hometomove",
            name="EstimatedVolume",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="customers",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hometomove",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="inventaire_items",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Housing_inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=50)),
                ("numberOfItems", models.IntegerField()),
                (
                    "totalVolumeOfItems",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "HomeToMove_fk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventaire.hometomove",
                    ),
                ),
            ],
        ),
    ]
