# Generated by Django 4.1.7 on 2023-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaire", "0007_hometomove_estimatedvolume_alter_customers_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventaire_items",
            name="place",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
