# Generated by Django 4.1.7 on 2023-04-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0030_piece_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imageArticle', models.ImageField(blank=True, null=True, upload_to='img_inventaire')),
            ],
        ),
        migrations.RemoveField(
            model_name='mission',
            name='article',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='user',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='image_item',
            new_name='imagePiece',
        ),
        migrations.DeleteModel(
            name='Contenu',
        ),
        migrations.DeleteModel(
            name='Inventaire_items',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.AddField(
            model_name='articles',
            name='place',
            field=models.ManyToManyField(to='inventaire.piece'),
        ),
    ]
