# Generated by Django 4.1.7 on 2023-04-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0031_articles_remove_mission_article_remove_mission_user_and_more'),
    ]


