# Generated by Django 4.1.7 on 2023-04-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0033_remove_articles_lieu_articles_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='place',
        ),
        migrations.AddField(
            model_name='piece',
            name='article',
            field=models.ManyToManyField(to='inventaire.articles'),
        ),
    ]
