# Generated by Django 4.1.7 on 2023-04-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0034_remove_articles_place_piece_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='nom',
            new_name='nomArticle',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='piece',
            new_name='nomPiece',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='slug',
            new_name='slugPiece',
        ),
    ]
