# Generated by Django 4.1.7 on 2023-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0035_rename_nom_articles_nomarticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='nomPieceArticle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
