# Generated by Django 4.1.7 on 2023-04-04 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaire', '0039_rename_user_mission_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionValidee', models.BooleanField(default=False)),
                ('dateMissionValisee', models.DateTimeField(blank=True, null=True)),
                ('articles', models.ManyToManyField(to='inventaire.mission')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
