# Generated by Django 4.1.7 on 2023-04-05 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaire', '0044_rename_panier_commandeclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteArticle', models.IntegerField(default=1)),
                ('articlesMission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.articles')),
                ('pieceMission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.missionpiece')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
