# Generated by Django 4.1.7 on 2023-04-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0046_articlesv2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesv2',
            name='slugArticle',
        ),
    ]
