# Generated by Django 4.1.7 on 2023-04-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0047_remove_articlesv2_slugarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlesV2',
        ),
    ]
