# Generated by Django 4.1.7 on 2023-04-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0050_piece_articles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='Articles_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventaire.articlesv2'),
        ),
    ]
