# Generated by Django 4.1.7 on 2023-04-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0053_détaillistingclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='détaillistingclient',
            name='piecesPanier',
        ),
    ]
