# Generated by Django 4.1.7 on 2023-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0054_remove_détaillistingclient_piecespanier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='détaillistingclient',
            name='dateMissionValisee',
        ),
        migrations.RemoveField(
            model_name='détaillistingclient',
            name='missionValidee',
        ),
        migrations.AlterField(
            model_name='détaillistingclient',
            name='articlesClient',
            field=models.ManyToManyField(to='inventaire.articles'),
        ),
    ]
