# Generated by Django 4.1.7 on 2023-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0059_alter_articlesv2_piece_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesv2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
