# Generated by Django 4.1.7 on 2023-04-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0062_rename_piecemission_missionarticle_piecemissiona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='article',
        ),
    ]
