# Generated by Django 4.1.7 on 2023-04-18 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaire', '0069_remove_articlesv2_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesv2',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
