# Generated by Django 4.1.7 on 2023-04-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0074_piece_utilisateur'),
    ]


