# Generated by Django 4.1.7 on 2023-04-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0076_remove_articlesv2_user_remove_piece_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandeclient',
            old_name='dateMissionValisee',
            new_name='dateMissionValidee',
        ),
    ]
