# Generated by Django 4.1.7 on 2023-04-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0077_rename_datemissionvalisee_commandeclient_datemissionvalidee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='détaillistingclient',
            name='articlesClient',
        ),
        migrations.RemoveField(
            model_name='détaillistingclient',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='missionarticle',
            name='articlesMission',
        ),
        migrations.RemoveField(
            model_name='missionarticle',
            name='pieceMissionA',
        ),
        migrations.RemoveField(
            model_name='missionarticle',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='ArticlesV2',
        ),
        migrations.DeleteModel(
            name='DétailListingClient',
        ),
        migrations.DeleteModel(
            name='MissionArticle',
        ),
    ]
