# Generated by Django 4.1.7 on 2023-04-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0080_alter_missionpiece_commande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpiece',
            name='commande_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.commandeclient'),
        ),
    ]
